[2023-08-31T00:05:15.026+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:04:40.141518+00:00/task_id=extract_listings permission to 509
[2023-08-31T00:05:15.027+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:04:40.141518+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:04:40.141518+00:00/task_id=extract_listings'
[2023-08-31T00:05:15.069+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:04:40.141518+00:00/task_id=extract_listings permission to 509
[2023-08-31T00:05:15.070+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:04:40.141518+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:04:40.141518+00:00/task_id=extract_listings'
[2023-08-31T00:05:15.110+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-08-31T00:04:40.141518+00:00 [queued]>
[2023-08-31T00:05:15.118+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-08-31T00:04:40.141518+00:00 [queued]>
[2023-08-31T00:05:15.119+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-08-31T00:05:15.133+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_listings> on 2023-08-31 00:04:40.141518+00:00
[2023-08-31T00:05:15.140+0000] {standard_task_runner.py:57} INFO - Started process 876 to run task
[2023-08-31T00:05:15.146+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'extract_listings', 'manual__2023-08-31T00:04:40.141518+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmpietzjgy6']
[2023-08-31T00:05:15.158+0000] {standard_task_runner.py:85} INFO - Job 69: Subtask extract_listings
[2023-08-31T00:05:15.244+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:04:40.141518+00:00/task_id=extract_listings permission to 509
[2023-08-31T00:05:15.245+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:04:40.141518+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:04:40.141518+00:00/task_id=extract_listings'
[2023-08-31T00:05:15.249+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-08-31T00:04:40.141518+00:00 [running]> on host 716b876f3aa6
[2023-08-31T00:05:15.383+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='extract_listings' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T00:04:40.141518+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T00:04:40.141518+00:00'
[2023-08-31T00:05:15.387+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/autotrader_extract.py", line 26, in extract_listings
    credentials = service_account.Credentials.from_service_account_info(credentials_dict)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/oauth2/service_account.py", line 243, in from_service_account_info
    signer = _service_account_info.from_dict(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 59, in from_dict
    signer = crypt.RSASigner.from_service_account_info(data)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/crypt/base.py", line 114, in from_service_account_info
    return cls.from_string(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/crypt/_cryptography_rsa.py", line 132, in from_string
    key = _helpers.to_bytes(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_helpers.py", line 111, in to_bytes
    raise exceptions.InvalidValue(
google.auth.exceptions.InvalidValue: None could not be converted to bytes
[2023-08-31T00:05:15.410+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Autotrader_ETL_DAG, task_id=extract_listings, execution_date=20230831T000440, start_date=20230831T000515, end_date=20230831T000515
[2023-08-31T00:05:15.427+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 69 for task extract_listings (None could not be converted to bytes; 876)
[2023-08-31T00:05:15.438+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-31T00:05:15.464+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
