[2023-08-31T23:14:52.580+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:14:33.541534+00:00/task_id=insert_raw_data_into_listings_raw permission to 509
[2023-08-31T23:14:52.581+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:14:33.541534+00:00/task_id=insert_raw_data_into_listings_raw permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:14:33.541534+00:00/task_id=insert_raw_data_into_listings_raw'
[2023-08-31T23:14:52.614+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:14:33.541534+00:00/task_id=insert_raw_data_into_listings_raw permission to 509
[2023-08-31T23:14:52.615+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:14:33.541534+00:00/task_id=insert_raw_data_into_listings_raw permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:14:33.541534+00:00/task_id=insert_raw_data_into_listings_raw'
[2023-08-31T23:14:52.642+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.insert_raw_data_into_listings_raw manual__2023-08-31T23:14:33.541534+00:00 [queued]>
[2023-08-31T23:14:52.651+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.insert_raw_data_into_listings_raw manual__2023-08-31T23:14:33.541534+00:00 [queued]>
[2023-08-31T23:14:52.652+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-31T23:14:52.666+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): insert_raw_data_into_listings_raw> on 2023-08-31 23:14:33.541534+00:00
[2023-08-31T23:14:52.675+0000] {standard_task_runner.py:57} INFO - Started process 474 to run task
[2023-08-31T23:14:52.678+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'insert_raw_data_into_listings_raw', 'manual__2023-08-31T23:14:33.541534+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmpy1tiin1b']
[2023-08-31T23:14:52.681+0000] {standard_task_runner.py:85} INFO - Job 116: Subtask insert_raw_data_into_listings_raw
[2023-08-31T23:14:52.728+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:14:33.541534+00:00/task_id=insert_raw_data_into_listings_raw permission to 509
[2023-08-31T23:14:52.729+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:14:33.541534+00:00/task_id=insert_raw_data_into_listings_raw permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:14:33.541534+00:00/task_id=insert_raw_data_into_listings_raw'
[2023-08-31T23:14:52.731+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.insert_raw_data_into_listings_raw manual__2023-08-31T23:14:33.541534+00:00 [running]> on host 1a0e8b05e04d
[2023-08-31T23:14:52.817+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='insert_raw_data_into_listings_raw' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T23:14:33.541534+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T23:14:33.541534+00:00'
[2023-08-31T23:14:52.828+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-08-31T23:14:52.832+0000] {base.py:73} INFO - Using connection ID 'google_cloud' for task execution.
[2023-08-31T23:14:52.834+0000] {gcs_to_bigquery.py:375} INFO - Using existing BigQuery table for storing data...
[2023-08-31T23:14:52.878+0000] {gcs_to_bigquery.py:379} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'autotrader-toyota-dashboard', 'datasetId': 'autotrader_staging', 'tableId': 'listings_raw'}, 'sourceFormat': 'NEWLINE_DELIMITED_JSON', 'sourceUris': ['gs://autotrader-raw/autotrader-raw-2023-08-31.json'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'price', 'type': 'STRING'}, {'name': 'odometer', 'type': 'STRING'}, {'name': 'year', 'type': 'STRING'}, {'name': 'model', 'type': 'STRING'}, {'name': 'type', 'type': 'STRING'}, {'name': 'suburb', 'type': 'STRING'}, {'name': 'state', 'type': 'STRING'}]}}}
[2023-08-31T23:14:52.880+0000] {bigquery.py:1596} INFO - Inserting job ***_Autotrader_ETL_DAG_insert_raw_data_into_listings_raw_2023_08_31T23_14_33_541534_00_00_8e1b927f6fcaf1a9bd9e60b05182253a
[2023-08-31T23:14:55.184+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 438, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: Failed to parse JSON: No object found when new array is started.; BeginArray returned false; Parser terminated before end of string File: autotrader-raw-2023-08-31.json
[2023-08-31T23:14:55.205+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Autotrader_ETL_DAG, task_id=insert_raw_data_into_listings_raw, execution_date=20230831T231433, start_date=20230831T231452, end_date=20230831T231455
[2023-08-31T23:14:55.218+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 116 for task insert_raw_data_into_listings_raw (400 Error while reading data, error message: Failed to parse JSON: No object found when new array is started.; BeginArray returned false; Parser terminated before end of string File: autotrader-raw-2023-08-31.json; 474)
[2023-08-31T23:14:55.266+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-31T23:14:55.287+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
