[2023-12-03T00:32:57.875+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:32:56.472585+00:00/task_id=extract_listings permission to 509
[2023-12-03T00:32:57.876+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:32:56.472585+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:32:56.472585+00:00/task_id=extract_listings'
[2023-12-03T00:32:57.903+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:32:56.472585+00:00/task_id=extract_listings permission to 509
[2023-12-03T00:32:57.904+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:32:56.472585+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:32:56.472585+00:00/task_id=extract_listings'
[2023-12-03T00:32:57.924+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T00:32:56.472585+00:00 [queued]>
[2023-12-03T00:32:57.930+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T00:32:56.472585+00:00 [queued]>
[2023-12-03T00:32:57.931+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-03T00:32:57.942+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_listings> on 2023-12-03 00:32:56.472585+00:00
[2023-12-03T00:32:57.948+0000] {standard_task_runner.py:57} INFO - Started process 429 to run task
[2023-12-03T00:32:57.950+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'extract_listings', 'manual__2023-12-03T00:32:56.472585+00:00', '--job-id', '1366', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmp_wtg6nk0']
[2023-12-03T00:32:57.952+0000] {standard_task_runner.py:85} INFO - Job 1366: Subtask extract_listings
[2023-12-03T00:32:57.991+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:32:56.472585+00:00/task_id=extract_listings permission to 509
[2023-12-03T00:32:57.992+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:32:56.472585+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:32:56.472585+00:00/task_id=extract_listings'
[2023-12-03T00:32:57.993+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T00:32:56.472585+00:00 [running]> on host 172bfe53c091
[2023-12-03T00:32:58.065+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='extract_listings' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T00:32:56.472585+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-03T00:32:56.472585+00:00'
[2023-12-03T00:33:00.218+0000] {logging_mixin.py:151} INFO - None
[2023-12-03T00:33:00.236+0000] {logging_mixin.py:151} INFO - []
[2023-12-03T00:33:00.255+0000] {python.py:194} INFO - Done. Returned value was: list index out of range
[2023-12-03T00:33:00.263+0000] {xcom.py:661} ERROR - Object of type IndexError is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-12-03T00:33:00.265+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 178, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'IndexError'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2485, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type IndexError is not JSON serializable
[2023-12-03T00:33:00.273+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Autotrader_ETL_DAG, task_id=extract_listings, execution_date=20231203T003256, start_date=20231203T003257, end_date=20231203T003300
[2023-12-03T00:33:00.284+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1366 for task extract_listings (Object of type IndexError is not JSON serializable; 429)
[2023-12-03T00:33:00.297+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-03T00:33:00.319+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
