[2023-12-03T02:51:56.308+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T02:23:50.193724+00:00/task_id=extract_listings permission to 509
[2023-12-03T02:51:56.309+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T02:23:50.193724+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T02:23:50.193724+00:00/task_id=extract_listings'
[2023-12-03T02:51:56.342+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T02:23:50.193724+00:00/task_id=extract_listings permission to 509
[2023-12-03T02:51:56.343+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T02:23:50.193724+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T02:23:50.193724+00:00/task_id=extract_listings'
[2023-12-03T02:51:56.364+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T02:23:50.193724+00:00 [queued]>
[2023-12-03T02:51:56.372+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T02:23:50.193724+00:00 [queued]>
[2023-12-03T02:51:56.373+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-03T02:51:56.386+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_listings> on 2023-12-03 02:23:50.193724+00:00
[2023-12-03T02:51:56.393+0000] {standard_task_runner.py:57} INFO - Started process 1920 to run task
[2023-12-03T02:51:56.396+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'extract_listings', 'manual__2023-12-03T02:23:50.193724+00:00', '--job-id', '1403', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmp_urkp_6h']
[2023-12-03T02:51:56.398+0000] {standard_task_runner.py:85} INFO - Job 1403: Subtask extract_listings
[2023-12-03T02:51:56.448+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T02:23:50.193724+00:00/task_id=extract_listings permission to 509
[2023-12-03T02:51:56.448+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T02:23:50.193724+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T02:23:50.193724+00:00/task_id=extract_listings'
[2023-12-03T02:51:56.450+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T02:23:50.193724+00:00 [running]> on host 172bfe53c091
[2023-12-03T02:51:56.536+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='extract_listings' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T02:23:50.193724+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-03T02:23:50.193724+00:00'
[2023-12-03T02:51:58.546+0000] {logging_mixin.py:151} INFO - 1
[2023-12-03T02:52:02.585+0000] {logging_mixin.py:151} INFO - 2
[2023-12-03T02:52:06.228+0000] {logging_mixin.py:151} INFO - 3
[2023-12-03T02:52:08.817+0000] {logging_mixin.py:151} INFO - 4
[2023-12-03T02:52:11.651+0000] {logging_mixin.py:151} INFO - 5
[2023-12-03T02:52:14.907+0000] {logging_mixin.py:151} INFO - 6
[2023-12-03T02:52:17.680+0000] {logging_mixin.py:151} INFO - 7
[2023-12-03T02:52:21.074+0000] {logging_mixin.py:151} INFO - 8
[2023-12-03T02:52:24.042+0000] {logging_mixin.py:151} INFO - 9
[2023-12-03T02:52:26.983+0000] {logging_mixin.py:151} INFO - 10
[2023-12-03T02:52:29.803+0000] {logging_mixin.py:151} INFO - 11
[2023-12-03T02:52:34.267+0000] {logging_mixin.py:151} INFO - 12
[2023-12-03T02:52:36.963+0000] {logging_mixin.py:151} INFO - 13
[2023-12-03T02:52:39.996+0000] {logging_mixin.py:151} INFO - 14
[2023-12-03T02:52:42.852+0000] {logging_mixin.py:151} INFO - 15
[2023-12-03T02:52:54.970+0000] {logging_mixin.py:151} INFO - 16
[2023-12-03T02:52:58.073+0000] {logging_mixin.py:151} INFO - 17
[2023-12-03T02:53:01.427+0000] {logging_mixin.py:151} INFO - 18
[2023-12-03T02:53:04.469+0000] {logging_mixin.py:151} INFO - 19
[2023-12-03T02:53:07.555+0000] {logging_mixin.py:151} INFO - 20
[2023-12-03T02:53:10.322+0000] {logging_mixin.py:151} INFO - 21
[2023-12-03T02:53:13.138+0000] {logging_mixin.py:151} INFO - 22
[2023-12-03T02:53:16.196+0000] {logging_mixin.py:151} INFO - 23
[2023-12-03T02:53:18.905+0000] {logging_mixin.py:151} INFO - 24
[2023-12-03T02:53:21.710+0000] {logging_mixin.py:151} INFO - 25
[2023-12-03T02:53:24.319+0000] {logging_mixin.py:151} INFO - 26
[2023-12-03T02:53:27.354+0000] {logging_mixin.py:151} INFO - 27
[2023-12-03T02:53:30.160+0000] {logging_mixin.py:151} INFO - 28
[2023-12-03T02:53:32.905+0000] {logging_mixin.py:151} INFO - 29
[2023-12-03T02:53:35.620+0000] {logging_mixin.py:151} INFO - 30
[2023-12-03T02:53:38.567+0000] {logging_mixin.py:151} INFO - 31
[2023-12-03T02:53:41.337+0000] {logging_mixin.py:151} INFO - 32
[2023-12-03T02:53:43.924+0000] {logging_mixin.py:151} INFO - 33
[2023-12-03T02:53:46.652+0000] {logging_mixin.py:151} INFO - 34
[2023-12-03T02:53:49.615+0000] {logging_mixin.py:151} INFO - 35
[2023-12-03T02:53:56.449+0000] {python.py:194} INFO - Done. Returned value was: Error loading page with status code 500
[2023-12-03T02:53:56.456+0000] {xcom.py:661} ERROR - Object of type Exception is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-12-03T02:53:56.458+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 178, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'Exception'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2485, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Exception is not JSON serializable
[2023-12-03T02:53:56.468+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Autotrader_ETL_DAG, task_id=extract_listings, execution_date=20231203T022350, start_date=20231203T025156, end_date=20231203T025356
[2023-12-03T02:53:56.490+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1403 for task extract_listings (Object of type Exception is not JSON serializable; 1920)
[2023-12-03T02:53:56.534+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-03T02:53:56.556+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
