[2023-12-03T00:24:50.347+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:24:15.293333+00:00/task_id=extract_listings permission to 509
[2023-12-03T00:24:50.348+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:24:15.293333+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:24:15.293333+00:00/task_id=extract_listings'
[2023-12-03T00:24:50.374+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:24:15.293333+00:00/task_id=extract_listings permission to 509
[2023-12-03T00:24:50.374+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:24:15.293333+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:24:15.293333+00:00/task_id=extract_listings'
[2023-12-03T00:24:50.393+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T00:24:15.293333+00:00 [queued]>
[2023-12-03T00:24:50.399+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T00:24:15.293333+00:00 [queued]>
[2023-12-03T00:24:50.400+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-03T00:24:50.410+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_listings> on 2023-12-03 00:24:15.293333+00:00
[2023-12-03T00:24:50.416+0000] {standard_task_runner.py:57} INFO - Started process 316 to run task
[2023-12-03T00:24:50.418+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'extract_listings', 'manual__2023-12-03T00:24:15.293333+00:00', '--job-id', '1355', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmpkwadwu2e']
[2023-12-03T00:24:50.420+0000] {standard_task_runner.py:85} INFO - Job 1355: Subtask extract_listings
[2023-12-03T00:24:50.462+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:24:15.293333+00:00/task_id=extract_listings permission to 509
[2023-12-03T00:24:50.462+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:24:15.293333+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:24:15.293333+00:00/task_id=extract_listings'
[2023-12-03T00:24:50.464+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T00:24:15.293333+00:00 [running]> on host 172bfe53c091
[2023-12-03T00:24:50.538+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='extract_listings' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T00:24:15.293333+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-03T00:24:15.293333+00:00'
[2023-12-03T00:24:51.520+0000] {logging_mixin.py:151} INFO - https://www.autotrader.com.au/car/car/13477536/toyota/hiace/wa/osborne-park/van
[2023-12-03T00:24:51.731+0000] {logging_mixin.py:151} INFO - 404
[2023-12-03T00:24:51.731+0000] {python.py:194} INFO - Done. Returned value was: Error loading listing url with status code 200
[2023-12-03T00:24:51.740+0000] {xcom.py:661} ERROR - Object of type Exception is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-12-03T00:24:51.741+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 178, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'Exception'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2485, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Exception is not JSON serializable
[2023-12-03T00:24:51.758+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Autotrader_ETL_DAG, task_id=extract_listings, execution_date=20231203T002415, start_date=20231203T002450, end_date=20231203T002451
[2023-12-03T00:24:51.768+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1355 for task extract_listings (Object of type Exception is not JSON serializable; 316)
[2023-12-03T00:24:51.797+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-03T00:24:51.825+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
