[2023-08-31T03:18:48.844+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T03:18:37.037528+00:00/task_id=load_to_gcp_bucket permission to 509
[2023-08-31T03:18:48.845+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T03:18:37.037528+00:00/task_id=load_to_gcp_bucket permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T03:18:37.037528+00:00/task_id=load_to_gcp_bucket'
[2023-08-31T03:18:48.871+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T03:18:37.037528+00:00/task_id=load_to_gcp_bucket permission to 509
[2023-08-31T03:18:48.872+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T03:18:37.037528+00:00/task_id=load_to_gcp_bucket permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T03:18:37.037528+00:00/task_id=load_to_gcp_bucket'
[2023-08-31T03:18:48.904+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.load_to_gcp_bucket manual__2023-08-31T03:18:37.037528+00:00 [queued]>
[2023-08-31T03:18:48.912+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.load_to_gcp_bucket manual__2023-08-31T03:18:37.037528+00:00 [queued]>
[2023-08-31T03:18:48.913+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-31T03:18:48.924+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_gcp_bucket> on 2023-08-31 03:18:37.037528+00:00
[2023-08-31T03:18:48.930+0000] {standard_task_runner.py:57} INFO - Started process 1047 to run task
[2023-08-31T03:18:48.932+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'load_to_gcp_bucket', 'manual__2023-08-31T03:18:37.037528+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmp0ravdx60']
[2023-08-31T03:18:48.934+0000] {standard_task_runner.py:85} INFO - Job 99: Subtask load_to_gcp_bucket
[2023-08-31T03:18:48.974+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T03:18:37.037528+00:00/task_id=load_to_gcp_bucket permission to 509
[2023-08-31T03:18:48.975+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T03:18:37.037528+00:00/task_id=load_to_gcp_bucket permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T03:18:37.037528+00:00/task_id=load_to_gcp_bucket'
[2023-08-31T03:18:48.977+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.load_to_gcp_bucket manual__2023-08-31T03:18:37.037528+00:00 [running]> on host 1a0e8b05e04d
[2023-08-31T03:18:49.054+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='load_to_gcp_bucket' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T03:18:37.037528+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T03:18:37.037528+00:00'
[2023-08-31T03:18:49.091+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/autotrader_extract.py", line 73, in load_to_gcp_bucket
    csv_file = csv.DictWriter(results_csv, fieldnames = results[0].keys())
IndexError: list index out of range
[2023-08-31T03:18:49.107+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Autotrader_ETL_DAG, task_id=load_to_gcp_bucket, execution_date=20230831T031837, start_date=20230831T031848, end_date=20230831T031849
[2023-08-31T03:18:49.118+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 99 for task load_to_gcp_bucket (list index out of range; 1047)
[2023-08-31T03:18:49.145+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-31T03:18:49.164+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
