[2023-08-31T00:16:28.044+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:15:55.065213+00:00/task_id=extract_listings permission to 509
[2023-08-31T00:16:28.044+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:15:55.065213+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:15:55.065213+00:00/task_id=extract_listings'
[2023-08-31T00:16:28.075+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:15:55.065213+00:00/task_id=extract_listings permission to 509
[2023-08-31T00:16:28.075+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:15:55.065213+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:15:55.065213+00:00/task_id=extract_listings'
[2023-08-31T00:16:28.114+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-08-31T00:15:55.065213+00:00 [queued]>
[2023-08-31T00:16:28.122+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-08-31T00:15:55.065213+00:00 [queued]>
[2023-08-31T00:16:28.123+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-08-31T00:16:28.136+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_listings> on 2023-08-31 00:15:55.065213+00:00
[2023-08-31T00:16:28.142+0000] {standard_task_runner.py:57} INFO - Started process 994 to run task
[2023-08-31T00:16:28.145+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'extract_listings', 'manual__2023-08-31T00:15:55.065213+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmpfnkh4mlk']
[2023-08-31T00:16:28.147+0000] {standard_task_runner.py:85} INFO - Job 73: Subtask extract_listings
[2023-08-31T00:16:28.193+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:15:55.065213+00:00/task_id=extract_listings permission to 509
[2023-08-31T00:16:28.194+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:15:55.065213+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T00:15:55.065213+00:00/task_id=extract_listings'
[2023-08-31T00:16:28.197+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-08-31T00:15:55.065213+00:00 [running]> on host 716b876f3aa6
[2023-08-31T00:16:28.302+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='extract_listings' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T00:15:55.065213+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T00:15:55.065213+00:00'
[2023-08-31T00:16:28.306+0000] {logging_mixin.py:151} INFO - {'type': 'service_account', 'project_id': None, 'private_key_id': None, 'private_key': None, 'client_email': None, 'client_id': None, 'auth_uri': 'https://accounts.google.com/o/oauth2/auth', 'token_uri': 'https://oauth2.googleapis.com/token', 'auth_provider_x509_cert_url': 'https://www.googleapis.com/oauth2/v1/certs', 'client_x509_cert_url': None, 'universe_domain': 'googleapis.com'}
[2023-08-31T00:16:28.307+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/autotrader_extract.py", line 31, in extract_listings
    credentials = service_account.Credentials.from_service_account_info(credentials_dict)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/oauth2/service_account.py", line 243, in from_service_account_info
    signer = _service_account_info.from_dict(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 59, in from_dict
    signer = crypt.RSASigner.from_service_account_info(data)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/crypt/base.py", line 114, in from_service_account_info
    return cls.from_string(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/crypt/_cryptography_rsa.py", line 132, in from_string
    key = _helpers.to_bytes(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_helpers.py", line 111, in to_bytes
    raise exceptions.InvalidValue(
google.auth.exceptions.InvalidValue: None could not be converted to bytes
[2023-08-31T00:16:28.324+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Autotrader_ETL_DAG, task_id=extract_listings, execution_date=20230831T001555, start_date=20230831T001628, end_date=20230831T001628
[2023-08-31T00:16:28.340+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 73 for task extract_listings (None could not be converted to bytes; 994)
[2023-08-31T00:16:28.358+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-31T00:16:28.382+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
