[2023-12-03T00:29:19.784+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:28:45.017173+00:00/task_id=extract_listings permission to 509
[2023-12-03T00:29:19.784+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:28:45.017173+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:28:45.017173+00:00/task_id=extract_listings'
[2023-12-03T00:29:19.815+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:28:45.017173+00:00/task_id=extract_listings permission to 509
[2023-12-03T00:29:19.816+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:28:45.017173+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:28:45.017173+00:00/task_id=extract_listings'
[2023-12-03T00:29:19.837+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T00:28:45.017173+00:00 [queued]>
[2023-12-03T00:29:19.845+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T00:28:45.017173+00:00 [queued]>
[2023-12-03T00:29:19.845+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-03T00:29:19.858+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_listings> on 2023-12-03 00:28:45.017173+00:00
[2023-12-03T00:29:19.865+0000] {standard_task_runner.py:57} INFO - Started process 383 to run task
[2023-12-03T00:29:19.868+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'extract_listings', 'manual__2023-12-03T00:28:45.017173+00:00', '--job-id', '1363', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmpcha0kg3n']
[2023-12-03T00:29:19.870+0000] {standard_task_runner.py:85} INFO - Job 1363: Subtask extract_listings
[2023-12-03T00:29:19.914+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:28:45.017173+00:00/task_id=extract_listings permission to 509
[2023-12-03T00:29:19.914+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:28:45.017173+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T00:28:45.017173+00:00/task_id=extract_listings'
[2023-12-03T00:29:19.916+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T00:28:45.017173+00:00 [running]> on host 172bfe53c091
[2023-12-03T00:29:19.989+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='extract_listings' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T00:28:45.017173+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-03T00:28:45.017173+00:00'
[2023-12-03T00:29:21.972+0000] {python.py:194} INFO - Done. Returned value was: list index out of range
[2023-12-03T00:29:21.981+0000] {xcom.py:661} ERROR - Object of type IndexError is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-12-03T00:29:21.983+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 178, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'IndexError'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2485, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type IndexError is not JSON serializable
[2023-12-03T00:29:21.990+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Autotrader_ETL_DAG, task_id=extract_listings, execution_date=20231203T002845, start_date=20231203T002919, end_date=20231203T002921
[2023-12-03T00:29:22.000+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1363 for task extract_listings (Object of type IndexError is not JSON serializable; 383)
[2023-12-03T00:29:22.051+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-03T00:29:22.084+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
